### PR TITLE
Attempt to translate Battle Start and End

### PR DESCRIPTION
**Pull request by sarabveer**
Tried it, I suck at Japanese

Don't merge yet, can someone please check and correct me?

### CODE REVIEW

**Comment by sarabveer** [comment]
So, I have to translate at that site?

**Comment by Renari** [comment]
Yes

**Comment by Fuusetsu** [comment]
Hello,

Sorry to disturb you, I would like to know if there is a way to translate this game. I have seen that you have create some patch for it. How do you use it? and Is it already ok ?

Thank you for your help and sorry I am not very good with this^^.

**Comment by Renari** [comment]
It's not ready yet.

**Pull request closed without merging**
